[package]
authors = ["Benno Fünfstück <benno.fuenfstueck@gmail.com>"]
name = "nix-index"
version = "0.1.0"

[[bin]]
doc = false
name = "nix-index"

[[bin]]
name = "nix-locate"

[[bin]]
name = "command-not-found"

[dependencies]
ansi_term = "0.9.0"
bincode = "1.0.0-alpha2"
brotli2 = "0.2.3"
byteorder = "1.0.0"
clap = "2.20.5"
error-chain = "0.10.0"
futures = "0.1.10"
grep = "0.1.5"
isatty = "0.1.3"
memchr = "1.0.1"
ordermap = "0.2.8"
regex = "0.2.1"
rustc-serialize = "0.3.22"
separator = "0.3.1"
serde = "0.9.7"
serde_derive = "0.9.7"
serde_json = "0.9.8"
stderr = "0.7.0"
tokio-core = "0.1.4"
tokio-retry = "0.0.5"
tokio-timer = "0.1.0"
void = "1.0.2"
xdg = "2.0.0"
xml-rs = "0.4.1"
xz2 = "0.1.2"
zstd = "0.4.3"

[dependencies.hyper]
branch = "master"
git = "https://github.com/hyperium/hyper"

[[example]]
name = "nix-index-debug"

[profile]

[profile.release]
debug = true
